src/Fortran-interface/bml_allocate_m.F90
src/Fortran-interface/bml_copy_m.F90
src/Fortran-interface/bml_transpose_m.F90
src/Fortran-interface/bml_types_m.F90

Let's disable the destructor in the type `bml_matrix_t` again ( :-1: ), requiring the users to use explicit deallocation routines in order to avoid memory leaks, but restoring compatibility with the buggy gfortran compiler. ( :+1: ).

Remove destructor

---

.travis.yml
README.md
src/C-interface/bml_allocate.c
src/C-interface/dense/bml_allocate_dense.c
src/C-interface/dense/bml_allocate_dense_typed.c
src/C-interface/ellpack/bml_allocate_ellpack.c
src/C-interface/ellpack/bml_allocate_ellpack_typed.c
src/C-interface/ellsort/bml_allocate_ellsort.c
src/C-interface/ellsort/bml_allocate_ellsort_typed.c

We require >=OpenMP-3.1 which was added to gcc-4.7. I made a note of
that in the README and removed the Travis compiler tests for <gcc-4.7.

Updated README and Travis-CI configuration

---

README.md

I started building binary packages for bml on OBS. This patch adds a
link to the package repository to the README file.

Add link to binary packages from OBS

---

build.sh

The EXTRA_LINK_FLAGS variable is not used in the CMake scripts. This
change removes it.

Cleanup build.sh script

---

src/Fortran-interface/bml_add_m.F90

For backwards compatibility, add the old bml_add() Fortran API as
deprecated.

Add deprecated bml_add API

---

CMakeLists.txt

I would like to release this as v1.1.0 so I can update the binary packages. Those will then go into the Travis-CI pipeline for progress.

Bumping version to v1.1.0

---

src/C-interface/ellpack/bml_submatrix_ellpack.c

The assert in the comparison function is not necessary. It is not
illegal to have to equal elements.

Remove unnecessary assert

---

src/Fortran-interface/bml_convert_m.F90

This patch changes the default of the `M` parameter for the
`bml_import_from` functions to `N`, the matrix size instead of the value
`0`.
Co-Authored-By: Jesse Grindstaff <grindstaff@lanl.gov>

Change defaults for `bml_import` Fortran API

---

tests/diagonalize_matrix_typed.c

This accommodates a failing test:
diagonalize-ellpack-single_complex:
Error in matrix diagonalization; fnorm(CDC^t-A) = 1.127484e-05

Relax single precision test tolerance

---

src/C-interface/dense/bml_norm_dense_typed.c
tests/inverse_matrix_typed.c
tests/transpose_matrix_typed.c

The inverse-dense-single_real test is failing for GCC 6 and OpenMP:
Error in matrix inverse; ssum(A*A_inverse) = -4.949570e-04
The test calculates the inverse, takes the product of the original
matrix and this inverse, and then computes the difference between N and
the sum of the squares of all matrix elements. In addition, with OpenMP
the implementation of the reduction affects the final result.
The final result, `ssum`, is then the accuracy of the inverse, the
matrix product `A*A^{-1}`, and the summed **squares** of the differences
of all elements. It's unclear to me exactly what accuracy to expect, but
the one we are using is not achieved for GCC 6 and OpenMP.

Relax tolerance for inverse test

---

README.md

Update some references that used to point to the `qmmd` organization to
the `lanl` organization.

Update references after moving to lanl

---

CMakeLists.txt

Consolidate logic to key on `CMAKE_BUILD_TYPE` for compiler flags.

Cleanup of CMakeLists.txt

---

src/Fortran-interface/bml_convert_m.F90

The code added in eb87291d7bcbc0b6c61b0a6f41ec22e07a92f025 is supposed
to insist on an M value for non-dense matrices and replace the default
of `m = 0` with `m = n`. However, due to incorrect logic this change
ended up setting `m` only for dense matrices and ignoring it otherwise.
The resulting bml matrix was incorrect.

bml_import does not copy M

---

src/Fortran-interface/bml_scale_m.F90

With change b93a366260afdd0ac0b0be4a5970e51173c9b7ed type matching scale
factors where introduced to the `bml_scale` APIs. However, only the
`bml_scale_two` Fortran interface was adapted but not the
`bml_scale_one` interfaces. This change adds the necessary APIs.

Add missing bml_scale Fortran interfaces

---

.travis.yml

The indentation of the .c and .h files should be verified by Travis-CI.
We used the command `indent` which simply indents all files instead of
the command `check_indent` which verifies that the indentation of those
files is correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/92)

Make Travis-CI check indentation

---

src/C-interface/dense/bml_normalize_dense_typed.c
src/C-interface/ellpack/bml_normalize_ellpack_typed.c
src/C-interface/ellsort/bml_normalize_ellsort_typed.c

Using a finite value to initialize min/max variables has the
disadvantage that any value might be too small or too large. Instead, we
should use the type dependent representable min/max value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/108)

Use appropriate values for initial min/max

---

CMakeLists.txt

The CMake script broke in 050250de8f14077291dc22b9a41092be95c6f22b. This
commit fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/119)

Fix the doc target

---

.travis.yml

On the `coverty_scan` branch we don't need to run the usual build steps.
This change disables them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/118)

Restrict build script

---

.travis.yml

The normal build and the coverty scan builds collide. Create a separate
branch again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/123)

Add back coverty branch for analysis

---

src/C-interface/ellpack/bml_utilities_ellpack_typed.c

The `FMT` string is unitialized. While the code should never reach a
point where it uses `FMT` in this state, it's safer to just initialize
it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/124)

Fix uninitialized string

---

.travis.yml

For debugging coverty issues it could be useful to know the contents of
the coverty log files. Since storing of build artifacts requires a more
complicated Travis-CI setup with S3 backed storage, a simple work around
is to print the contents of the log files so that their content is
visible in the build logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/130)

Print out coverty log files

---

.travis.yml

When running coverty scan the Travis-CI build matrix causes the scan to
run for every element of the matrix. This is unnecessary. This change
leverages the environment variables `COVERITY_SCAN_BRANCH` and
`TRAVIS_JOB_NUMBER` to determine whether a coverty scan is run and to
restrict a coverty scan to the first element of the build matrix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/133)

Restrict coverty scan with Travis-CI build matrix

---

.travis.yml
build.sh

This change introduces a new option to `build.sh` to set the number of
parallel test jobs to run. We leverage this option on Travis-CI to speed
up testing since we get 2 VCPUs per VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/132)

Run tests in parallel

---

.travis.yml

Before we can switch to trusty on Travis-CI, the coverage tools need to
be installed with the `--user` flag (see documentation of coveralls).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/136)

Install coveralls and codecov as user

---

src/C-interface/bml_parallel.h

Explicitly including mpi.h in bml_parallel.h due to issues with spack
build and dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/142)

Explicitly Including mpi.h

---

src/C-interface/bml_allocate.c

Does what is says ~on the tin~ in the title. Should fix issue #144.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/149)

Add an include-guard for <omp.h> in bml_allocate.c

---

tests/trace_matrix_typed.c

In the trace test the type of the trace is always `double` and we
should be using the correct version of `abs()` instead of the typed
version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/151)

Use correct version of abs()

---

build.sh

Some flags, particularly compiler flags, can have spaces in them and
should be quoted when passed to the `cmake` call. Previously this was
not happening which made it impossible to use several extra flags with
the build.sh script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/163)

Fix quoting of extra flags to build.sh

---

src/C-interface/bml_logger.h
src/C-interface/dense/bml_scale_dense_typed.c
src/C-interface/ellpack/bml_scale_ellpack_typed.c
src/C-interface/ellsort/bml_scale_ellsort_typed.c

When setting `BLAS_VENDOR=None` the build fails because some sources
do not include `bml_logger.h` for the `LOG_ERROR` macro. This change
adds an include to these sources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/162)

Add includes to fix building with NOBLAS

---

CMakeLists.txt
src/CMakeLists.txt
tests/CMakeLists.txt

The Fortran API potentially requires some additional link time
dependencies which are unnecessary for C applications but need to be
added to the C linker arguments. This change splits the Fortran code
into a separate library.
Fixes: #143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/160)

Split Fortran from C API

---

src/bml.pc.in

Since we split the library into two, the linker flags advertised in
the pkg file need to be updated and the new `libbml_fortran` library
added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/164)

Add Fortran library to linker flags

---

src/Fortran-interface/bml_introspection_m.F90

Added bml_get_element_type() and bml_get_element_precision() on the fortran interface.
So far this could be done with bml_get_precision() which gives back a number where: 
0 = uninitialized 
1 = single real 
2 = double real 
3 = single complex 
4 = double complex 
bml_get_element_type() instead will return either "real" or "complex" and 
bml_get_element_precision() will return an integer. In the case the elements are real(8) 
it will return 8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/199)

Added bml_get_element_type() and bml_get_element_precision()

---

src/C-interface/bml_logger.c

The size argument in the `snprintf` function equals the size of the
string buffer which might leave the buffer unterminated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/205)

CID-170916: Fix buffer length

---

tests/bml_test.c

We can't shut down the bml before we call the test function (which
will use bml functions). Instead we should store the test result, shut
down the bml and then return the result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/211)

Fix order of `bml_shutdown()` in test driver

---

build.sh

The testing step requires that the bml is built with BML_TESTING
turned on. This change adds a simple sanity check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/212)

Test for BML_TESTING when testing

---

src/C-interface/dense/bml_allocate_dense_typed.c
src/C-interface/ellpack/bml_allocate_ellpack_typed.c
src/C-interface/ellsort/bml_allocate_ellsort_typed.c

Removed pragma omp for random allocation of matrices. Now the results are repeatable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/216)

Removed pragma omp for random allocation of matrices.

---

.travis.yml

It is not necessary to test all builds for memory leaks with
valgrind. Assuming that the compiler does not introduce leaks, one
tested job tells us already what we want to know: Whether the code is
leaking memory or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/224)

Only test on build for memory leaks

---

.travis.yml

It is not necessary to run the other build stages on the
`coverty_scan` branch. It is tracking the `master` branch which we
will assume is green.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/230)

Run only coverty_scan stage

---

src/C-interface/dense/bml_allocate_dense_typed.c

MAGMA matrices memory allocation was not set to 0 in some cases, which was not consistent with non-MAGMA based dense format. It also lead to test failures on Summit@OLCF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/243)

Bux fix in memory allocation for MAGMA matrices

---

src/C-interface/dense/bml_normalize_dense_typed.c

Added missing variable in omp pragmas that were needed to compile with both 
magma and omp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/252)

Added missing argument when compiling with magma and omp

---

CMakeLists.txt
build.sh
cmake/test_complex.c
src/typed.h

The Nvidia compilers don't support complex types for device. This
change adds an option to disable building of complex types. In
addition CMake will now verify that the compile can deal with complex
types.
This implementation is pretty crude. If complex types are not built,
then the corresponding types will be mapped to their real valued
counter parts in `typed.h`. The library will still contain functions
that have a `complex` in their name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/255)

Make build of complex types optional

---

src/C-interface/ellpack/CMakeLists.txt

Preprocessing flags were different between ellpack and elsort. 
Now we are passing "${COMPILE_FLAGS} ${OpenMP_C_FLAGS}"
to both
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/258)

Passing different flags to ellpack and ellsort fixed

---

src/C-interface/ellsort/bml_multiply_ellsort_typed.c

issue was fixed by:
converting "omp parallel" region to "omp parallel for" region
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/249)

fixed omp index issue in bml_multiply_ellsort_typed.c

---

CMakeLists.txt

In case we need to know what version CMake was used to build the bml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/259)

Print CMake version (for debugging)

---

src/C-interface/bml_add.c
src/C-interface/bml_add.h
src/C-interface/dense/bml_add_dense.c
src/C-interface/dense/bml_add_dense.h
src/C-interface/dense/bml_add_dense_typed.c
src/C-interface/ellblock/bml_add_ellblock.c
src/C-interface/ellblock/bml_add_ellblock.h
src/C-interface/ellblock/bml_add_ellblock_typed.c
src/C-interface/ellpack/bml_add_ellpack.c
src/C-interface/ellpack/bml_add_ellpack.h
src/C-interface/ellpack/bml_add_ellpack_typed.c
src/C-interface/ellsort/bml_add_ellsort.c
src/C-interface/ellsort/bml_add_ellsort.h
src/C-interface/ellsort/bml_add_ellsort_typed.c
src/Fortran-interface/bml_c_interface_m.F90

This change adjusts the types in `bml_add` so that the pointer `A` is
`const`, but the value of `A` is mutable, and both the pointer and the
value of `B` is `const`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/265)

Fix `const` types in `bml_add`

---

build.sh
indent.sh

This change updates the `indent.sh` script so that it indents only
files that are tracked in git. This avoids indenting files that are
build artifacts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/264)

Update `indent.sh` script

---

indent.sh

Was accidentally dropped in 972e231a8663cee792d2c653d750ddd459e92e1f.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/269)

Add the C header files

---

src/C-interface/bml_add.c
src/C-interface/bml_add.h
src/C-interface/dense/bml_add_dense.c
src/C-interface/dense/bml_add_dense.h
src/C-interface/dense/bml_add_dense_typed.c
src/C-interface/ellblock/bml_add_ellblock.c
src/C-interface/ellblock/bml_add_ellblock.h
src/C-interface/ellblock/bml_add_ellblock_typed.c
src/C-interface/ellpack/bml_add_ellpack.c
src/C-interface/ellpack/bml_add_ellpack.h
src/C-interface/ellpack/bml_add_ellpack_typed.c
src/C-interface/ellsort/bml_add_ellsort.c
src/C-interface/ellsort/bml_add_ellsort.h
src/C-interface/ellsort/bml_add_ellsort_typed.c
src/Fortran-interface/bml_add_m.F90

This change adjusts the types in `bml_add_norm` so that the pointer
`A` is `const`, but the value of `A` is mutable, and both the pointer
and the value of `B` is `const`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/267)

Fix `const` types in `bml_add_norm`

---

.travis.yml
indent.sh
src/C-interface/bml_add.h
src/C-interface/dense/bml_add_dense.h
src/C-interface/ellblock/bml_add_ellblock.h
src/C-interface/ellpack/bml_add_ellpack.h
src/C-interface/ellsort/bml_add_ellsort.h

For local testing it can be convenient to be able to set the `emacs`
binary explicitly. This change introduces the environment variable
`EMACS` to specify which `emacs` binary to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/270)

Make `emacs` binary configurable

---

src/C-interface/bml_add.h
src/C-interface/dense/bml_add_dense.h
src/C-interface/ellblock/bml_add_ellblock.h
src/C-interface/ellpack/bml_add_ellpack.h
src/C-interface/ellsort/bml_add_ellsort.h

Some of the C header files were using incorrect indentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/271)

Fix incorrect indentation

---

src/C-interface/bml_allocate.c
src/C-interface/bml_allocate.h
src/C-interface/dense/bml_allocate_dense.c
src/C-interface/dense/bml_allocate_dense.h
src/C-interface/dense/bml_allocate_dense_typed.c
src/C-interface/ellblock/bml_allocate_ellblock.c
src/C-interface/ellblock/bml_allocate_ellblock.h
src/C-interface/ellblock/bml_allocate_ellblock_typed.c
src/C-interface/ellpack/bml_allocate_ellpack.c
src/C-interface/ellpack/bml_allocate_ellpack.h
src/C-interface/ellpack/bml_allocate_ellpack_typed.c
src/C-interface/ellsort/bml_allocate_ellsort.c
src/C-interface/ellsort/bml_allocate_ellsort.h
src/C-interface/ellsort/bml_allocate_ellsort_typed.c

This change adjusts the types in `bml_allocate` so that the const type
modifier applies to the correct part of the type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/276)

Fix `const` types in `bml_allocate`

---

README.md
docs/index.md

Waffle.io shut down on May 16, 2019 [1]. This change removes all
references to this service.
[1] https://help.waffle.io/waffle-shutdown/waffle-shutdown-tldr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/290)

Remove defunct waffle.io references

---

src/C-interface/bml_inverse.c
src/C-interface/bml_inverse.h
src/C-interface/dense/bml_inverse_dense.c
src/C-interface/dense/bml_inverse_dense.h
src/C-interface/dense/bml_inverse_dense_typed.c
src/C-interface/ellblock/bml_inverse_ellblock.c
src/C-interface/ellblock/bml_inverse_ellblock.h
src/C-interface/ellblock/bml_inverse_ellblock_typed.c
src/C-interface/ellpack/bml_inverse_ellpack.c
src/C-interface/ellpack/bml_inverse_ellpack.h
src/C-interface/ellpack/bml_inverse_ellpack_typed.c

This change removes the `const` qualifiers for the `bml_inverse` type
functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/289)

Remove `const` qualifiers

---

.travis.yml
build.sh

This change splits the valgrind tests, which take by far the longest,
into four smaller test jobs to speed up testing on Travis-CI. This
speedup relies on the fact that Travis-CI runs the test matrix in
parallel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/304)

Split valgrind testing for improved performance

---

.dir-locals.el

This change adds more settings for the Emacs editor for Fortran
related indentation settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/306)

Add Fortran related indentation settings

---

src/C-interface/dense/bml_export_dense_typed.c

When bml_expoert_to_dense was invoked and bml was compiled with magma, the original bml matrix 
was modified (transposed). We are adding another "back" transpose to go back to the original matrix. Another solution would be to allocate an auxiliary matrix and let the original unchanged, but this implies the use of extra memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/309)

Solved a bug in bml_export_to_dense when using magma

---

src/C-interface/dense/bml_diagonalize_dense.c
src/C-interface/dense/bml_multiply_dense_typed.c
src/C-interface/dense/bml_transpose_dense_typed.c
tests/C-tests/diagonalize_matrix_typed.c

Issue was not showing up for small problems,
but the diagonalize matrix test problem would fail for large
matrices of size >~ 1500.
Add calls to magma_queue_sync() in a few places to avoid race
conditions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/317)

Fix race condition in call to MAGMA eigensolver

---

src/C-interface/bml_utilities.c
src/C-interface/ellblock/bml_import_ellblock_typed.c
src/C-interface/ellblock/bml_multiply_ellblock_typed.c
src/typed.h
tests/C-tests/diagonalize_matrix_typed.c
tests/C-tests/multiply_banded_matrix_typed.c

This PR fixes compile warnings about floating point type inconsistencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/336)

Fix type/ format warnings

---

src/C-interface/ellpack/bml_submatrix_ellpack.c
tests/C-tests/multiply_banded_matrix_typed.c
tests/C-tests/multiply_matrix_typed.c
tests/C-tests/multiply_matrix_x2_typed.c
tests/C-tests/test_bml_gemm_typed.c

Remove unnecessary 'const' qualifiers to fix clang warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/335)

Fix clang warnings about const

---

.travis.yml
tests/C-tests/CMakeLists.txt
tests/Fortran-tests/CMakeLists.txt
tests/Fortran-tests/testf.F90

We should run the Fortran tests with valgrind to make sure we don't
introduce memory issues by using the Fortran API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/340)

Add valgrind tests for Fortran

---

CMakeLists.txt
src/C-interface/ellpack/bml_multiply_ellpack_typed.c
tests/C-tests/CMakeLists.txt
tests/Fortran-tests/CMakeLists.txt

To ease readability, refactor `valgrind` command line arguments into
the main `CMakeLists.txt` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/343)

Refactor valgrind command line arguments

---

CMakeLists.txt

The quoted path is not working as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/345)

Fix `valgrind` command line argument

---

src/C-interface/ellsort/bml_multiply_ellsort_typed.c

We should investigate whether the call to `bml_multiply_x2_ellsort` is
necessary or could be written slightly differently so we don't have to
free the trace which is not used here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/347)

Fix memory leak

---

ci-images/build/Dockerfile

While not needed for CI itself, it's necessary for running the
container yourself and be able to git clone from https.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/364)

Install ssl certificates

---

src/Fortran-interface/bml_interface_m.F90
src/Fortran-interface/bml_types_m.F90

Adding missing CSR type for Fortran interface
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/377)

Added CSR type for Fortran interface

---

CMakeLists.txt
src/Fortran-interface/bml_getters_m.F90
tests/Fortran-tests/io_matrix_typed.F90

***Nick, Christian: Please check the first of these in particular to make sure it won't introduce a memory leak and recommend a different fix if this won't work. -- Mike
In src/Fortran-interface/bml_getters_m.F90:
Remove deallocate() lines from get_diagonal and get_row methods as Intel compiled code throws an error during tests indicating that diagonal_ptr cannot be deallocated.
In tests/Fortran-tests/io_matrix_typed.F90:
Changed the temporary file name to use date_and_time() time stamp instead of getpid() for portability. Intel getpid() requires including another module and throws an error during tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/387)

Modifications to enable build with ANL JLSE intel/2019 + mkl/2020.04.30.001 modules

---

src/C-interface/bml_allocate.c

The `bml_free_ptr()` function was only used in the Fortran interface
and did the same as the `bml_free_memory()` function. This change
removes the former.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/391)

Remove duplicate function

---

.circleci/config.yml
.github/workflows/CI.yml

This will allow us to modify the build environment from git since we
don't depend on our own images anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/392)

Do not use pre-built images for CI

---

.github/workflows/CI.yml

This change uses the latest CI image (tagged `master`) for CI runs.
Updating the CI environment can be done now through a PR. Once the PR
is merged, the `master` image will be updated on `hub.docker.com` and
subsequent CI runs will use this new image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/420)

Use the latest CI image from `master`

---

.github/workflows/CI.yml

The `container` job runs in a trusted environment since it needs to
access the DockerHub secrets so it can push the built image. This has
potential security implication.
Please only approve the `container` job if the PR is
- From a trusted party
- Involves a change in `Dockerfile`
- Does not print or make available in any way the environment secrets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/433)

Add clarification to container job

---

.github/workflows/CI.yml
src/C-interface/bml_parallel.c
src/C-interface/bml_parallel.h
src/C-interface/csr/CMakeLists.txt
src/C-interface/csr/bml_parallel_csr.c
src/C-interface/csr/bml_parallel_csr.h
src/C-interface/csr/bml_parallel_csr_typed.c
src/C-interface/dense/bml_parallel_dense.c
src/C-interface/dense/bml_parallel_dense.h
src/C-interface/dense/bml_parallel_dense_typed.c
src/C-interface/ellblock/CMakeLists.txt
src/C-interface/ellblock/bml_parallel_ellblock.c
src/C-interface/ellblock/bml_parallel_ellblock.h
src/C-interface/ellblock/bml_parallel_ellblock_typed.c
src/C-interface/ellpack/bml_parallel_ellpack.c
src/C-interface/ellpack/bml_parallel_ellpack.h
src/C-interface/ellpack/bml_parallel_ellpack_typed.c
src/C-interface/ellsort/bml_parallel_ellsort.c
src/C-interface/ellsort/bml_parallel_ellsort.h
src/C-interface/ellsort/bml_parallel_ellsort_typed.c
src/typed.h
tests/C-tests/CMakeLists.txt
tests/C-tests/bml_test.c
tests/C-tests/bml_test.h
tests/C-tests/mpi_sendrecv.c
tests/C-tests/mpi_sendrecv.h
tests/C-tests/mpi_sendrecv_typed.c

MPI point-to-point send/recv for BML matrices
of all formats
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/438)

Add functionality to send/recv matrices

---

.github/workflows/CI.yml

So far we are testing only the `single_real` float type for the MPI
tests. This change adds the other float types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/452)

Add testing of remaining float types to MPI tests

---

.github/workflows/CI.yml

This change will enable CI testing on branches that do not correspond
to a PR. This might be helpful when developing a PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/451)

Do not restrict CI runs to `master` only

---

.github/workflows/CI.yml
Dockerfile
clang.list
cmake.list
emacs.list
refresh-ci-images.sh
toolchain.list

* Xenial is going out of regular maintenance mid-year 2021 [1]
* Xenial is EOL for LLVM since March 28 2021 [2]
* Xenial does not support >gcc-9 [3].
This change updates the CI image to using Bionic.
[1] https://ubuntu.com/about/release-cycle
[2] https://apt.llvm.org/
[3] https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=xenial
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/454)

Update CI image to Bionic

---

.github/workflows/CI.yml

This is a follow-on of lanl/bml#454.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/456)

Switch back to using the `master` CI image

---

README.md
docs/index.md

We dropped coverage analysis when we moved away from Travis-CI. As per
our discussion [1] we will not re-enable those tests. This change
removes the now obsolete status badges for the removed tests.
[1] https://github.com/lanl/bml/discussions/463

Remove obsolete badges

---

.github/workflows/CI.yml
Dockerfile
clang.list
cmake.list
emacs.list
prepare-container.sh
toolchain.list

This change removes the custom built container from the GitHub
workflows and instead configures the build environment during the CI
run itself. This has the advantage that we can modify the build
environment in a PR and use is for that same PP in CI.

Build CI environment in workflow

---

CMakeLists.txt

Remove obsolete `BML_OLD` flag

---

CMakeLists.txt

This flag can be turned on explicitly with the `BML_COVERAGE` flag.
Closes: lanl/bml#404

Remove default `--coverage` flag

---

CMakeLists.txt
build.sh
src/C-interface/bml_diagonalize.c
src/C-interface/bml_introspection.c
src/C-interface/bml_introspection.h
src/C-interface/bml_norm.c
src/C-interface/bml_setters.c
src/C-interface/dense/bml_introspection_dense.c
src/C-interface/dense/bml_introspection_dense.h
src/C-interface/distributed2d/CMakeLists.txt
src/C-interface/distributed2d/bml_allocate_distributed2d.c
src/C-interface/distributed2d/bml_diagonalize_distributed2d.c
src/C-interface/distributed2d/bml_diagonalize_distributed2d.h
src/C-interface/distributed2d/bml_diagonalize_distributed2d_typed.c
src/C-interface/distributed2d/bml_norm_distributed2d.c
src/C-interface/distributed2d/bml_norm_distributed2d.h
src/C-interface/distributed2d/bml_setters_distributed2d.c
src/C-interface/distributed2d/bml_setters_distributed2d.h
tests/C-tests/CMakeLists.txt
tests/C-tests/diagonalize_matrix_typed.c

Diagonalization requires ScaLAPACK.
ScaLAPACK library should be specified using
export EXTRA_LINK_FLAGS=...
since cmake build has currently not capability to find it.

Distributed2d diagonalization and norm functions

---

.github/workflows/container.yaml

This is not necessary anymore.

Remove special CI environment for docker

---

.github/workflows/container.yaml

If we do not restrict to the main repository, forked repositories will
try to run this workflow and fail because they are missing the
necessary credentials to push the image to Docker Hub.

Only build container in main repository

---

CMakeLists.txt
build.sh
scripts/build_mkl_gpu.sh
src/C-interface/dense/bml_multiply_dense_typed.c
src/typed.h

Build scripts added in scripts/ directory, build_mkl_gpu.sh. Currently, the link flags are manually set, will add check of libraries in cmake. 
New marcos are added to support the cblas_?gemm calls:
1) The cblas_zgemm and cblas_cgemm functions uses the MKL_complex8/16 data type, Hence, MKL_T, MKL_REAL, MKL_IMAG marco are introduced to convert the data type. 
2)MKL_ADDESS is added to get address of the variables for cblas_zgemm/cgemm. 
3)G_BLAS is added to select the corresponding dgemm for different data type. Since C_BLAS is existing for the internal-blas, I used G_BLAS instead.

Add MKL GPU support for the dense format

---

.github/workflows/container.yaml

This change builds and uploads the experimental CI images to Docker
Hub.
They can be used by running:
$ IMAGE=nicolasbock/bml:focal ./scripts/run-local-docker-container.sh

Build and upload the tech preview CI images

---

Dockerfile-hirsute
Dockerfile-impish
scripts/prepare-container-hirsute.sh
scripts/prepare-container-impish.sh

Both Hirsute and Impish ship with emacs-1:27.1 and we do not need to
use a separate PPA to install emacs27.

Update experimental CI images

---

.github/workflows/CI.yaml
scripts/ci-defaults.sh
scripts/ci-gcc-4.8-test-1.sh
scripts/ci-gcc-4.8-test-2.sh
scripts/ci-gcc-4.8-test-3.sh
scripts/ci-gcc-4.8-test-4.sh

By moving the logic of the CI test jobs into separate scripts it will
become easier to locally test a particular job by simply running its
associated script.

Move CI test jobs into scripts

---

.github/workflows/trigger-qmd.yaml

We need to test the `qmd` library with the most recent `bml` library.
This change will trigger the CI workflow in the `qmd-progress`
repository when a pull request is merged into the `master` branch.

Trigger qmd CI when updating `master`

---

.github/workflows/CI.yaml

Remove job dependencies and fast fail so we get a more complete CI
picture in cases where jobs are failing. This should help in preparing
a fixed pull request.

Remove job dependencies

---

build.sh

Closes #517 
Example for switching the generator:
```
CMAKE_ARGS="-G Ninja" ./build.sh compile
```

Allow pass-through CMake arguments in build script

---

.dir-locals.el
build.sh

Commit 72338c2750af601e9af3256adfdacde040a69e38 introduced a
regression which broke the `install` verb of the `build.sh` script.
Running `make install` implies building the library whereas `cmake
--install` does not and expects the project to be built.

Fix missing build targets

---

scripts/build_spock_offload_cce.sh
scripts/build_tulip_offload_cce.sh
scripts/setenv_spock_offload.sh
scripts/setenv_tulip_offload.sh
src/C-interface/ellpack/bml_add_ellpack_typed.c
src/C-interface/ellpack/bml_allocate_ellpack.c
src/C-interface/ellpack/bml_allocate_ellpack.h
src/C-interface/ellpack/bml_allocate_ellpack_typed.c
src/C-interface/ellpack/bml_multiply_ellpack_typed.c

Revised the code to build on ORNL spock and Cray/HPE tulip:
o Use the same offload code path for CRAY_SDK macro as for INTEL_SDK macro
o Modify bml_add_norm_ellpack() and bml_add_identity_ellpack()
to follow similar syntax as in bml_add_ellpack()
- Note: Tests needed for bml_add_norm_ellpack() and bml_add_identity_ellpack()
o Create a typed bml_deallocate_ellpack() (see issue #524)
o Add scripts for building on spock
- scripts/setenv_spock_offload.sh
- scripts/build_spock_offload_cce.sh
o Add scripts for building on tulip
- scripts/setenv_tulip_offload.sh
- scripts/build_tulip_offload_cce.sh

Modifications to support additional offload builds

---

src/C-interface/bml_copy.c
src/C-interface/csr/bml_copy_csr_typed.c
src/C-interface/csr/bml_setters_csr.h
src/C-interface/csr/bml_setters_csr_typed.c

This PR:
1. Fixes an issue with bml_copy where we check for storage size using the initial column dimension. For CSR, this check is done internally, since individual rows need not have the same size.
2. Modifies bml_setters_csr to avoid allocating space for a dense row when setting sparse row entries from a dense array.

Fix copy and setters

---

scripts/update_tags.sh

Since the script was moved into the `scripts` directory, the `basedir`
needs to be updated to include files starting from the repository root
directory.

Fix paths in tag update script

---

scripts/build_olcf_summit_gnu_mgma_openblas.sh

* adapt to OS upgrade
* add option to jsrun to enable 'inverse' dense tests
* fixes #539 on Summit

Fix Summit build script

---

src/C-interface/dense/bml_parallel_dense_typed.c

I have to admit I don't fully understand why this change makes a difference, but it does on some platforms at least where the test suite fails without that fix.
Note that it is already done this way for other matrix formats.

Change the way MPI datatype is built for dense case

---

CMakeLists.txt

Fixes a bug where the link step fails when building on LANL Darwin cluster, due to missing CUDA libs in the link line

Add CUDA libraries when linking if CUDA is found by cmake

---

src/C-interface/distributed2d/bml_diagonalize_distributed2d_typed.c
tests/C-tests/diagonalize_matrix_typed.c
tests/C-tests/normalize_matrix_typed.c

Size of work array had to be fixed. In addition, that size had to be increased
to work around possible bug in ScaLapack.
Failure was not seen for matrix size used in test suite, but only for larger
matrices.

Fix issues with ScaLapack call

---

tests/Fortran-tests/testf.F90

Even number needed for testing 2 x 2 data distribution

Fix matrix size for fortran tests

---

.github/workflows/stale.yaml

The permissions might have to be set explicitly in the workflow [1].
[1] https://github.com/actions/stale#recommended-permissions

Fix permission issue with stale workflow

---

README.rst

Add RTD badge

---

README.rst
docs/source/conf.py

Fix for `sphinx<2` (as used on RTD)

---

build.sh

This change brings the naming of `BLA_VENDOR` in alignment with the
`FindBLAS.cmake` module. The old name `BLAS_VENDOR` is still supported and will
be preferred over `BLA_VENDOR` if both are defined.

Add `BLA_VENDOR` to build.sh

---

scripts/build_crusher_offload_cce.sh
scripts/setenv_crusher_offload.sh

o source scripts/setenv_crusher_offload.sh
o bash scripts/build_crusher_offload_cce.sh

Build scripts for crusher offload

---

scripts/build_lassen_xl_offload.sh
scripts/setenv_lassen_offload.sh
src/C-interface/ellblock/bml_add_ellblock_typed.c
src/C-interface/ellblock/bml_multiply_ellblock_typed.c
src/C-interface/ellpack/bml_add_ellpack_typed.c
src/C-interface/ellpack/bml_element_multiply_ellpack_typed.c
src/C-interface/ellpack/bml_multiply_ellpack_typed.c
src/C-interface/ellpack/bml_normalize_ellpack.c
tests/Fortran-tests/io_matrix_typed.F90

This PR applies code changes to enable building BML with IBM compilers and openMP offload support. 
* Build requires setting "BML_COMPLEX =no" to avoid linker issues.
* Tested on Lassen

Enable use of IBM XL compilers with openMP Offload support

---

tests/C-tests/CMakeLists.txt
tests/C-tests/test_openmp_offload.c

Verify simple OpenMP loop running on device,
to check OpenMP offload working

Add simple test to verify OpenMP offload

---

.github/workflows/CI.yaml

Pull requests will be checked in CI anyway. The additional `push` even
check duplicates CI runs for pull requests that live in the `lanl/bml`
repository.

Only check `push` events on `master` branch

---

build.sh
scripts/build_iris_offload_oneapi.sh
scripts/build_lassen_xl_offload.sh
scripts/build_mkl_gpu.sh
scripts/example_build.sh
scripts/indent.sh
scripts/magma_build.sh
scripts/pre-commit
scripts/prepare-container-focal.sh
scripts/prepare-container.sh
scripts/run-local-docker-container.sh

The pre-commit hook script needs to be copied locally to:
$ cp scripts/pre-commit .git/hooks/pre-commit
It will run the linter before committing.
Since the linter takes a while to complete, it can be helpful to disable
this check if desired. Adding the `--no-verify` command line option to
`git commit` will do that:
$ git commit --no-verify [options]

Add pre-commit hook script

---

.github/workflows/CI.yaml
build.sh
scripts/ci-gcc-11-C-double-complex.sh
scripts/ci-gcc-11-C-double-real.sh
scripts/ci-gcc-11-C-single-complex.sh
scripts/ci-gcc-11-C-single-real.sh
scripts/ci-gcc-11-Fortran-double-complex.sh
scripts/ci-gcc-11-Fortran-double-real.sh
scripts/ci-gcc-11-Fortran-single-complex.sh
scripts/ci-gcc-11-Fortran-single-real.sh
scripts/prepare-container-macos.sh

We keep running into issues only seen on OS X systems. Since Travis-CI
offers OS X based tests, we can leverage it to fix our OS X build
issues. This change enables testing on OS X.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/172)

Enable CI testing on OS X

---

build.sh

This change adds a basic "sanity" check to `build.sh` to verify whether the
chosen compile options make sense or not.
Closes: lanl/bml#619

Add sanity check for `build.sh` options

---

CMakeLists.txt
src/C-interface/bml_logger.c.indented
src/C-interface/bml_logger.h.indented
src/C-interface/ellpack/bml_add_ellpack_typed.c
src/C-interface/ellpack/bml_multiply_ellpack_typed.c

o Use is_above_threshold() to support complex thresholding
o Add "-foffload=-misa=sm_35" to GNU offload flags to avoid sm_30 arch error

Minor revisions to cuSPARSE code and offload flags

---

.github/workflows/CI.yaml

This change stores the output of a failed lint job as an artifact.
Closes: lanl/bml#647

Store result of failed lint job

---

src/C-interface/dense/bml_diagonalize_dense.c

Fixes omission in 0254bbf2fb3a2eb49e734ad2f17772ea5c384de3

Add missing include statement

---

src/C-interface/ellpack/bml_setters_ellpack_typed.c
src/C-interface/ellpack/bml_threshold_ellpack_typed.c
src/C-interface/ellpack/bml_trace_ellpack_typed.c

o Address offload bottlenecks in the following from crusher hackathon:
- bml_set_diagonal_ellpack()
- bml_threshold_ellpack()
- bml_trace_ellpack()

Optimize openmp offload for rocsparse

---

.ecp-gitlab-ci.yml

Default (magma2.6.2) not working for BML

Specify magma version to use for CI on Ascent@OLCF

---

CMakeLists.txt

* was used to setup unused variable
* may fail to be found in lm sometimes

Remove check for fabs by cmake

---

src/C-interface/distributed2d/bml_diagonalize_distributed2d_typed.c

ELPA uses a macro named double_complex, as we do in BML

Fix conflict with ELPA macro

---

CMakeLists.txt
src/CMakeLists.txt

This change moves the CMake package definition (for use in other CMake based projects) to the project's root directory. This puts the definition in the same place as the `pkg-config` based definitions.
Closes: https://github.com/lanl/bml/issues/684

Move CMake package definitions

---

CMakeLists.txt
scripts/build_crusher_rocsparse_cce.sh
src/C-interface/ellpack/bml_multiply_ellpack_typed.c
src/typed.h

o rocsparse_xprune does not support unsorted matrices in rocm 5.3
- sort the matrix after multiplication and before pruning

Fix rocsparse multiply using rocm 5.3

---

.devcontainer/devcontainer.json
Dockerfile-focal

Using root in the container will create files owned by root on the host
which is quite inconvenient. Instead, use a non-root user, ubuntu, which
will be mapped by VSCode to the current UID/PID.

Add local user to devcontainer

---

.devcontainer/devcontainer.json

Which is much faster than building a fresh container image every time.

Pull devcontainer from Docker Hub

---

src/C-interface/ellpack/bml_add_ellpack_typed.c
src/C-interface/ellpack/bml_allocate_ellpack.h
src/C-interface/ellpack/bml_allocate_ellpack_typed.c
src/C-interface/ellpack/bml_copy_ellpack_typed.c
src/C-interface/ellpack/bml_multiply_ellpack_typed.c
src/typed.h

Working rocsparse add and multiply fix
o New bml_add_ellpack() method using rocsparse
o New bml_sort_rocsparse_ellpack() method to sort csr column indices
o New bml_prune_rocsparse_ellpack() method to threshold the csr matrix
o Modify bml_multiply_ellpack() rocpsarse to use the new sort and prune
- Addresses issue where unsorted array might be passed, potentially causing errors
o Progress benchmarks produce correct results using rocsparse

Rocsparse add targeting OLCF Frontier

---

scripts/install_rocsparse_headers_olcf.sh

Temporary fix on OLCF machines for rocsparse header bug, until rocm 5.5 is deployed
Run the following from the bml/ root dir:
bash scripts/install_rocsparse_headers_olcf.sh

Add script to install rocsparse headers on OLCF machines

---

scripts/indent.sh

o The indent script wasn't parsing the input file list correctly
- add "shift" statement to fix this

Fix bug in indent.sh script

---

src/C-interface/ellpack/bml_add_ellpack_typed.c
src/C-interface/ellpack/bml_allocate_ellpack_typed.c
src/C-interface/ellpack/bml_element_multiply_ellpack_typed.c
src/C-interface/ellpack/bml_multiply_ellpack_typed.c
src/C-interface/ellpack/bml_scale_ellpack_typed.c

o bml_add_ellpack arrays allocated but not freed
o bml_multiply_ellpack arrays allocated but not freed o Also increase efficiency of a target region in bml_prune_rocsparse_ellpack

Fix OMP offload build memory leaks

---

src/C-interface/ellpack/bml_allocate_ellpack_typed.c

Fix rocSPARSE bug causing progress issues
Issues:
o Ellpack progress tests were failing for rocSPARSE build
o Progress benchmark was also failing for N>=6000
Fix:
o bml_sort_rocsparse_ellpack was obtaining nnz from host array
o changed this to obtain nnz from device array

Fix progress rocsparse tests

---

src/C-interface/csr/bml_norm_csr_typed.c
src/C-interface/ellblock/bml_norm_ellblock_typed.c
src/C-interface/ellpack/bml_norm_ellpack_typed.c

* Fixed various bugs in norm calculation that implicitly assumed dense storage for sparse matrices.
* This fix should enable correct norm calculations on arbitrary sparse matrices.

Bug fixes for norm calculation.

---

src/C-interface/csr/bml_allocate_csr_typed.c
src/C-interface/ellblock/bml_allocate_ellblock_typed.c
src/C-interface/ellblock/bml_multiply_ellblock_typed.c
src/C-interface/ellpack/bml_allocate_ellpack_typed.c

This PR introduces a new strategy for constructing sparse (arbitrary) random matrices. This fixes issues with the previous approach that assumed the column indexes per row are contiguous (as in dense matrices). The PR also corrects potential issues with our test framework due to the above assumption. This PR resolves issue #715.

Fix random matrix

---

tests/Fortran-tests/add_matrix_typed.F90

Check absolute values instead of relative since we now have truly sparse matrices

Fix Fortran addition test

---

scripts/build_crusher_magma_cce.sh
scripts/setenv_crusher_magma_cce.sh

cce/15.0.1 required instead of default to avoid segfaults rocm/5.1.0 required instead of default to avoid diagonalization tests failures (double and double complex)

Add script for cray compiler on AMD GPU

---

tests/C-tests/CMakeLists.txt
tests/C-tests/test_magma.c

To be run upfront to make sure magma works for BML

Add simple magma test

---

CMakeLists.txt

o This fixes a build bug seen using MKL for BLAS/LAPACK 
o Some syev functions (e.g. C_SSYEV) are being used without setting macros in CMakeLists.txt
o The fix adds the lines to define these macros

Use cmake LAPACK function finders for Intel MKL

---

CMakeLists.txt
build.sh
cmake/FindHYPRE.cmake
scripts/build_lassen_xl_offload_whypre.sh
scripts/build_olcf_summit_gnu_offload_openblas_whypre.sh
scripts/setenv_lassen_offload.sh
src/C-interface/bml_logger.c
src/C-interface/ellpack/bml_add_ellpack.h
src/C-interface/ellpack/bml_add_ellpack_typed.c
src/C-interface/ellpack/bml_allocate_ellpack.h
src/C-interface/ellpack/bml_allocate_ellpack_typed.c
src/C-interface/ellpack/bml_multiply_ellpack.h
src/C-interface/ellpack/bml_multiply_ellpack_typed.c
src/C-interface/ellpack/bml_types_ellpack.h

This PR enables integrating hypre into BML to allow BML to access hypre's GPU capable sparse linear algebra routines, particularly, matrix multiplication and matrix addition.
* The approach should allow BML to use hypre for sparse linear algebra operations on NVIDIA, AMD and Intel GPUs. However, the current implementation targets NVIDIA GPUs. Minor edits/ additions are necessary to support AMD.
* Currently, hypre can be built in one precision at a time, so bml tests for multiple precisions will only pass for the precision for which hypre was built (if BML is built with hypre support).

Bml whypre

---

src/Fortran-interface/bml_fc_tools_m.F90
src/Fortran-interface/bml_utilities_m.F90

New compilers have f_c_string built in, renaming our function to avoid conflicts (issue #744)

Rename f_c_string to bml_f_c_string to avoid conflict (issue 744)

---

CMakeLists.txt
build.sh
src/C-interface/bml_allocate.c

Using the HAVE_POSIX_MEMALIGN code path results in ~1.7x slowdown of an MD code which frequently allocates arrays.
Require a new macro BML_USE_POSIX_MEMALIGN to be defined, to use the code path. Define the macro by default.

Require BML_USE_POSIX_MEMALIGN to use posix_memalign()

---

src/C-interface/bml_init.c
src/C-interface/bml_shutdown.c
src/C-interface/dense/bml_add_dense_typed.c
src/C-interface/dense/bml_allocate_dense_typed.c
src/C-interface/dense/bml_convert_dense_typed.c
src/C-interface/dense/bml_copy_dense_typed.c
src/C-interface/dense/bml_diagonalize_dense.c
src/C-interface/dense/bml_element_multiply_dense_typed.c
src/C-interface/dense/bml_export_dense.c
src/C-interface/dense/bml_export_dense_typed.c
src/C-interface/dense/bml_getters_dense_typed.c
src/C-interface/dense/bml_import_dense_typed.c
src/C-interface/dense/bml_inverse_dense_typed.c
src/C-interface/dense/bml_multiply_dense_typed.c
src/C-interface/dense/bml_norm_dense_typed.c
src/C-interface/dense/bml_normalize_dense_typed.c
src/C-interface/dense/bml_parallel_dense_typed.c
src/C-interface/dense/bml_scale_dense_typed.c
src/C-interface/dense/bml_setters_dense.c
src/C-interface/dense/bml_setters_dense_typed.c
src/C-interface/dense/bml_submatrix_dense_typed.c
src/C-interface/dense/bml_threshold_dense_typed.c
src/C-interface/dense/bml_trace_dense_typed.c
src/C-interface/dense/bml_transpose_dense_typed.c
src/C-interface/dense/bml_utilities_dense_typed.c
src/C-interface/ellpack/bml_submatrix_ellpack_typed.c

Added include file <stdbool.h> before the <magma_v2.h> include. On my newer gcc compilers, C did not understand what the bool data type meant, which is something that magma uses. Thus, I could not build without concluding this .h file.

Build bml with magma (v2.9) and newer gcc compiler (v 12.4.0)

---

.github/workflows/CI.yaml
.github/workflows/container.yaml
Dockerfile-noble
scripts/ci-clang-16-gfortran-14-C-double-complex.sh
scripts/ci-clang-16-gfortran-14-C-double-real.sh
scripts/ci-clang-16-gfortran-14-C-single-complex.sh
scripts/ci-clang-16-gfortran-14-C-single-real.sh
scripts/indent.sh
scripts/prepare-container-noble.sh

Add Noble container image
