- CMakeLists.txt
For release build type we don't want asserts.
> Disable debug (assert)

- src/C-interface/ellpack/bml_diagonalize_ellpack_typed.c
- tests/CMakeLists.txt
- tests/bml_test.c
- tests/bml_test.h
- tests/diagonalize_matrix_typed.c
- tests/set_diagonal.c
- tests/set_diagonal.h
- tests/set_diagonal_typed.c
- tests/set_row.c
- tests/set_row.h
- tests/set_row_typed.c
Added a test for the set_diagonal routine.
> added test for set diagonal

- .travis.yml
Travis-CI recently began upgrading their VMs to trusty. This patch
updates the Travis-CI configuration.
> Fix installed packages for Travis-CI instance

- README.md
I have added some details on our suggested workflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/99)
> Explain workflow better

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/97)
> Add authors and contributors to README

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/100)
> Add coverty configuration

- .travis.yml
- README.md
An alternative to codecov.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/109)
> Add coveralls code coverage tool

- .travis.yml
- Dangerfile
- Gemfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/110)
> Add Danger for commit linting

- Gemfile
- README.md
- webpage/index.md
Slight reformatting of how the various project badges are shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/111)
> Update the README

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/116)
> Add coverty badge

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/117)
> Add issue badge

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/115)
> Add version to coverty scan configuration

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/120)
> Add pull request badge

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/121)
> Fix PR badge

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/122)
> Another fix for coverty

- README.md
My LANL email address is not working anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/126)
> Updated email address

- .travis.yml
- src/C-interface/dense/bml_convert_dense.c
- src/C-interface/dense/bml_convert_dense_typed.c
- src/C-interface/ellpack/bml_convert_ellpack.c
- src/C-interface/ellpack/bml_convert_ellpack_typed.c
- src/C-interface/ellsort/bml_convert_ellsort.c
- src/C-interface/ellsort/bml_convert_ellsort_typed.c
This Travis-CI test verifies that the code is indented according to the
bml coding style making indentation a voting test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/127)
> Turn on `check_indent` test

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/128)
> Update the code citation (zenodo)

- README.md
You can never have enough badges...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/138)
> Add waffle.io badges

- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/139)
> Sync webpage with README

- README.md
- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/140)
> Add codacy badge

- README.md
- docs/index.md
The README should spell out which matrix types the library supports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/141)
> Add a list of supported matrix types

- CONTRIBUTING.md
- README.md
I copied the code contributing guidelines from the README file into a
separate file to make it easier to find this information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/146)
> Added contributing guidelines

- CMakeLists.txt
It can be useful to add custom link flags. This change adds a CMake
variable to specify such flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/152)
> Add custom link flags

- CMakeLists.txt
- build.sh
Changes in CMakeList.txt and build.sh to set the Fortran and C compiler 
flags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/154)
> small changes in names

- build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/156)
> Reorder help text to group flag related settings

- .travis.yml
- Dangerfile
- Gemfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/157)
> Updated Dangerfile and added more checks

- build.sh
The build script already knows how to build a shared library. Add a
help notice how to do that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/165)
> Add help on how to build a shared library

- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/168)
> Fix formatting of bml mailing list

- README.md
- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/169)
> Make formatting of ML reference consistent

- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/170)
> Fix index.md

- README.md
- docs/index.md
The waffle service recently changed their badge URL. This change
updates it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/173)
> Update waffle.io badge

- CMakeLists.txt
Closes: #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/174)
> Make Fortran API optional

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/176)
> Version bump to v1.2.3

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/183)
> Fix installation of danger on Travis-CI

- README.md
- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/186)
> Update bibtex reference

- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/185)
> Prettify mailing list link

- build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/184)
> Define undefined variables in build.sh

- build.sh
Removed readlink command in build.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/177)
> No readlink in build.sh

- examples/example2/Makefile
- examples/example2/main.cc
Simple C++ code illustrating how to use bml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/187)
> Added C++ example

- tests/CMakeLists.txt
- tests/bml_test.c
- tests/bml_test.h
- tests/multiply_matrix_x2.c
- tests/multiply_matrix_x2.h
- tests/multiply_matrix_x2_typed.c
- tests/test_multiply_x2.c
- tests/test_multiply_x2.h
Test for bml_multiply_x2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/190)
> Test for multiply_x2

- indent.sh
- src/Fortran-interface/bml_print_matrix_wrapper.c
- src/internal-blas/bml_gemm.c
- test-getter/ptr.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/188)
> Add examples to indent script

- Dangerfile
- Gemfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/197)
> Update danger checks

- .travis.yml
The result of the danger check will be in the required tests section anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/198)
> Ignore danger failures in Travis-CI script

- README.md
- example_build.sh
The idea of this PR is to provide instruction on how to use the example_build.sh script so that 
users don't modify the build.sh script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/200)
> Changed example_build and README

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/201)
> Version bump to v1.3.0

- update_tags.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/204)
> Switch to correct directory

- src/C-interface/bml_copy.c
- src/C-interface/bml_utilities.c
- src/C-interface/dense/bml_convert_dense_typed.c
- src/C-interface/dense/bml_getters_dense_typed.c
- src/C-interface/dense/bml_setters_dense_typed.c
- src/C-interface/ellpack/bml_convert_ellpack_typed.c
- src/C-interface/ellsort/bml_convert_ellsort_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/203)
> Error handling

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/207)
> Fixed CMakeLists.txt to properly use MKLROOT environment variable

- src/C-interface/dense/bml_utilities_dense_typed.c
- src/C-interface/ellpack/bml_utilities_ellpack_typed.c
- src/C-interface/ellsort/bml_utilities_ellsort_typed.c
Added ability to read MTX files that are symmetric.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/208)
> Modified reading of mtx files to handle symmetric type.

- CMakeLists.txt
- build.sh
- makeBuild.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/206)
> Enable CUDA detection in CMake script

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/217)
> Small indentation fix

- CMakeLists.txt
- src/C-interface/dense/bml_add_dense_typed.c
- src/C-interface/dense/bml_norm_dense_typed.c
- src/C-interface/dense/bml_normalize_dense_typed.c
- src/C-interface/dense/bml_threshold_dense_typed.c
- src/C-interface/dense/bml_trace_dense_typed.c
- src/C-interface/dense/bml_transpose_dense_typed.c
- src/C-interface/ellpack/bml_adjungate_triangle_ellpack_typed.c
- src/C-interface/ellpack/bml_multiply_ellpack_typed.c
- src/C-interface/ellpack/bml_norm_ellpack_typed.c
- src/C-interface/ellpack/bml_normalize_ellpack_typed.c
- src/C-interface/ellpack/bml_submatrix_ellpack.c
- src/C-interface/ellpack/bml_trace_ellpack_typed.c
- src/C-interface/ellpack/bml_transpose_ellpack_typed.c
- src/C-interface/ellsort/bml_add_ellsort_typed.c
- src/C-interface/ellsort/bml_adjungate_triangle_ellsort_typed.c
- src/C-interface/ellsort/bml_multiply_ellsort_typed.c
- src/C-interface/ellsort/bml_norm_ellsort_typed.c
- src/C-interface/ellsort/bml_normalize_ellsort_typed.c
- src/C-interface/ellsort/bml_submatrix_ellsort.c
- src/C-interface/ellsort/bml_submatrix_ellsort_typed.c
- src/C-interface/ellsort/bml_threshold_ellsort_typed.c
- src/C-interface/ellsort/bml_trace_ellsort_typed.c
- src/C-interface/ellsort/bml_transpose_ellsort_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/215)
> Some cleanup

- build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/218)
> Add --debug to build.sh script

- .travis.yml
- src/C-interface/dense/bml_multiply_dense_typed.c
- tests/bml_test.c
- tests/multiply_matrix_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/213)
> Gemm consistency

- src/bml.pc.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/219)
> Add URL to pkg-config

- .travis.yml
- install_packages.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/222)
> Introduce build stages

- .travis.yml
This stage is broken due to an unfortunate typo...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/223)
> Fix the Travis-CI coverage test

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/225)
> More tests

- .travis.yml
Only build documentation if we are building the `master` branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/226)
> Conditional build of docs

- src/C-interface/bml_allocate.c
- src/C-interface/bml_allocate.h
- src/C-interface/bml_types.h
- src/C-interface/dense/bml_allocate_dense.c
- src/C-interface/dense/bml_allocate_dense.h
- src/C-interface/dense/bml_allocate_dense_typed.c
- src/C-interface/dense/bml_convert_dense_typed.c
- src/C-interface/dense/bml_copy_dense_typed.c
- src/C-interface/dense/bml_import_dense_typed.c
- src/C-interface/dense/bml_threshold_dense_typed.c
- src/C-interface/dense/bml_transpose_dense_typed.c
- src/C-interface/ellpack/bml_allocate_ellpack.c
- src/C-interface/ellpack/bml_allocate_ellpack.h
- src/C-interface/ellpack/bml_allocate_ellpack_typed.c
- src/C-interface/ellpack/bml_copy_ellpack_typed.c
- src/C-interface/ellpack/bml_multiply_ellpack_typed.c
- src/C-interface/ellpack/bml_submatrix_ellpack_typed.c
- src/C-interface/ellpack/bml_transpose_ellpack_typed.c
- src/C-interface/ellsort/bml_allocate_ellsort.c
- src/C-interface/ellsort/bml_allocate_ellsort.h
- src/C-interface/ellsort/bml_allocate_ellsort_typed.c
- src/C-interface/ellsort/bml_copy_ellsort_typed.c
- src/C-interface/ellsort/bml_multiply_ellsort_typed.c
- src/C-interface/ellsort/bml_submatrix_ellsort_typed.c
- src/C-interface/ellsort/bml_transpose_ellsort_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/221)
> Generalize matrix dimensions (Issue #220)

- .travis.yml
This change activates the coverty scan again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/227)
> Re-add coverty scan

- Dangerfile
So we don't miss linting issues this change makes some of them fail
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/229)
> Stricter linting

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/232)
> Added paper to Readme

- LICENSE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/241)
> Changed LICENSE for Triad etc.

- .travis.yml
This change combines two build stages since they didn't really
conceptually differ anyway. This should make the build faster (since
stages are build sequentially), while not sacrificing any test
coverage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/246)
> Simplify build stages

- .travis.yml
Only publish with tags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/248)
> Only publish on tags

- src/C-interface/ellsort/bml_multiply_ellsort_typed.c
Code did not compile with the Intel compiler suite (version 18).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/250)
> Fix mixing for in omp parallel pragma.

- CODEOWNERS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/253)
> Add Jean-Luc as code reviewer

- src/C-interface/dense/bml_norm_dense_typed.c
The function
bml_sum_squares_submatrix_dense(const bml_matrix_dense_t *, const int)
had not been implemented for GPU using MAGMA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/254)
> Add missing MAGMA implemention of function

- src/C-interface/dense/bml_normalize_dense_typed.c
Previous implementation was very inefficient. This one still runs on
the CPU, but requires only one data transfer from GPU to CPU
(the whole matrix at once)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/256)
> Revisit implementation of gershgorin function for MAGMA build

- .dir-locals.el
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/275)
> Add dir-locals file for emacs

- .dir-locals.el
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/277)
> Add another indentation related variable

- src/C-interface/bml_adjungate_triangle.c
- src/C-interface/dense/bml_adjungate_triangle_dense.c
- src/C-interface/dense/bml_adjungate_triangle_dense_typed.c
- src/C-interface/ellpack/bml_adjungate_triangle_ellpack_typed.c
- src/C-interface/ellsort/bml_adjungate_triangle_ellsort.c
- src/C-interface/ellsort/bml_adjungate_triangle_ellsort_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/274)
> Const adjungate triangle

- src/C-interface/dense/bml_utilities_dense_typed.c
Code was incorrect. It was ignoring the low/high index for print
range, and also using a column major convention instead of
row major.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/307)
> Replace call to magma print function with print from CPU

- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/310)
> Move `test` stage earlier in the build process

- src/C-interface/bml_allocate.c
- src/C-interface/bml_export.c
- src/C-interface/bml_utilities.c
- tests/C-tests/CMakeLists.txt
- tests/C-tests/bml_test.c
- tests/C-tests/bml_test.h
- tests/C-tests/print_matrix.c
- tests/C-tests/print_matrix.h
- tests/C-tests/print_matrix_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/308)
> Add test for bml_print_bml_matrix functions

- indent.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/314)
> Fix file patter for indent script

- update_tags.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/315)
> Fix update tags script

- src/C-interface/bml_trace.c
- src/C-interface/bml_trace.h
- src/C-interface/dense/bml_trace_dense.c
- src/C-interface/dense/bml_trace_dense.h
- src/C-interface/dense/bml_trace_dense_typed.c
- src/C-interface/ellblock/bml_trace_ellblock.c
- src/C-interface/ellblock/bml_trace_ellblock.h
- src/C-interface/ellblock/bml_trace_ellblock_typed.c
- src/C-interface/ellpack/bml_submatrix_ellpack_typed.c
- src/C-interface/ellpack/bml_trace_ellpack.c
- src/C-interface/ellpack/bml_trace_ellpack.h
- src/C-interface/ellpack/bml_trace_ellpack_typed.c
- src/C-interface/ellsort/bml_submatrix_ellsort_typed.c
- src/C-interface/ellsort/bml_trace_ellsort.c
- src/C-interface/ellsort/bml_trace_ellsort.h
- src/C-interface/ellsort/bml_trace_ellsort_typed.c
- src/Fortran-interface/bml_c_interface_m.F90
- src/Fortran-interface/bml_trace_m.F90
- tests/C-tests/CMakeLists.txt
- tests/C-tests/bml_test.c
- tests/C-tests/bml_test.h
- tests/C-tests/test_trace_mult.c
- tests/C-tests/test_trace_mult.h
- tests/C-tests/test_trace_mult_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/313)
> Corrected traceMult

- src/C-interface/dense/bml_trace_dense_typed.c
Fixes issue #318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/319)
> Bug fix for bml_trace_dense with MAGMA

- tests/C-tests/CMakeLists.txt
- tests/C-tests/bml_test.c
- tests/C-tests/bml_test.h
- tests/C-tests/set_element.c
- tests/C-tests/set_element.h
- tests/C-tests/set_element_typed.c
Two things are added in this PR: 
- A test for set_element 
- A change in the /tests/CMakelist.txt that will allow us to "exclude" tests that are not 
applicable to a particular bml routine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/322)
> Set element

- example_build.sh
- src/Fortran-interface/bml_interface_m.F90
- src/Fortran-interface/bml_introspection_m.F90
- src/Fortran-interface/bml_types_m.F90
Added the ellsort type for the fortran interface
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/323)
> Added elsort type in fortran interface

- src/C-interface/ellblock/bml_allocate_ellblock.c
- src/C-interface/ellblock/bml_allocate_ellblock_typed.c
- src/C-interface/ellblock/bml_setters_ellblock_typed.c
- tests/C-tests/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/325)
> Fix ellblock set element

- src/C-interface/ellblock/bml_setters_ellblock_typed.c
- tests/C-tests/CMakeLists.txt
- tests/C-tests/diagonalize_matrix_typed.c
- tests/C-tests/inverse_matrix_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/329)
> Fix and activate test diagonalize for ellblock

- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/332)
> Add clang for C and C++ compilers

- src/C-interface/ellblock/bml_trace_ellblock.h
Fix typo in ELLBLOCK header guard
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/333)
> Fix typo in ELLBLOCK header guard

- tests/Fortran-tests/CMakeLists.txt
- tests/Fortran-tests/allocate_matrix.F90
- tests/Fortran-tests/convert_matrix_typed.F90
Fixing test for Fortran bml matrices allocations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/334)
> Fixed test for allocate

- build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/341)
> Travis verbose skipped

- src/C-interface/ellblock/bml_allocate_ellblock.c
Fix issue number #342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/346)
> Bug fix in computing ellblock number of blocks/row

- src/C-interface/ellblock/bml_allocate_ellblock.c
- src/C-interface/ellblock/bml_copy_ellblock_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/344)
> Ellblock memory

- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/349)
> Update coverty script

- tests/C-tests/bml_test.c
- tests/Fortran-tests/testf.F90
> Match matrix sizes for Fortran and C tests

- src/C-interface/ellsort/bml_getters_ellsort_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/351)
> Allocate using `bml_allocate_memory`

- .travis.yml
This branch simply tracks the master branch and we have done all of
the necessary testing already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/352)
> Do not test on ocverty branch

- src/C-interface/dense/bml_utilities_dense_typed.c
- src/C-interface/ellblock/bml_utilities_ellblock_typed.c
- src/C-interface/ellpack/bml_utilities_ellpack_typed.c
- src/C-interface/ellsort/bml_utilities_ellsort_typed.c
- tests/C-tests/CMakeLists.txt
- tests/C-tests/bml_test.c
- tests/C-tests/bml_test.h
- tests/C-tests/io_matrix.c
- tests/C-tests/io_matrix.h
- tests/C-tests/io_matrix_typed.c
Added missing files for test_io_matrix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/324)
> Added the suporting files for io_matrix

- README.md
- docs/index.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/356)
> Add CircleCI badge

- .circleci/config.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/355)
> Add dependencies to jobs

- .circleci/config.yml
- ci-images/build/Dockerfile
- ci-images/docs/Dockerfile
- ci-images/lint/Dockerfile
- refresh-ci-images.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/357)
> Add `docs` build job to CircleCI

- .circleci/config.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/358)
> Upgrade to version 2.1 schema in CircleCI

- src/Fortran-interface/bml_getters_m.F90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/348)
> Fix memory leak for getter

- .circleci/config.yml
- CMakeLists.txt
- ci-images/build/Dockerfile
- ci-images/build/clang.list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/363)
> Add clang test

- CMakeLists.txt
- scripts/convert-template.in
- src/Fortran-interface/CMakeLists.txt
- tests/Fortran-tests/CMakeLists.txt
- tests/Fortran-tests/README.md
Let cmake find python3 interpreter and use it explicitly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/367)
> Python3 fix

- src/C-interface/dense/bml_allocate_dense_typed.c
- src/C-interface/dense/bml_setters_dense_typed.c
- src/C-interface/dense/bml_utilities_dense_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/371)
> Implement missing functions calling MAGMA

- .circleci/config.yml
Needed for #372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/373)
> CI: disable docs build for now

- CMakeLists.txt
- documentation/Doxyfile.in
- src/BMLConfig.cmakein
- src/C-interface/dense/CMakeLists.txt
- src/C-interface/ellblock/CMakeLists.txt
- src/C-interface/ellpack/CMakeLists.txt
- src/C-interface/ellsort/CMakeLists.txt
- src/CMakeLists.txt
- src/Fortran-interface/CMakeLists.txt
- src/internal-blas/CMakeLists.txt
- test-getter/CMakeLists.txt
- tests/C-tests/CMakeLists.txt
- tests/Fortran-tests/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/372)
> cmake: export bml target

- .travis.yml
- src/BMLConfig.cmakein
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/375)
> cmake: fix OpenMP in exported target

- .circleci/config.yml
- CMakeLists.txt
- ci-images/docs/Dockerfile
Reverts lanl/bml#373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/374)
> Revert "CI: disable docs build for now"

- .circleci/config.yml
- Gemfile
- ci-images/build/Dockerfile
- ci-images/docs/Dockerfile
- ci-images/lint/Dockerfile
- refresh-ci-images.sh
* Add https transport for llvm ppa
* Fix setup of timezone (tzdata)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/390)
> Fix version 1.0 of the CI images

- .circleci/config.yml
- ci-images/build/Dockerfile
- ci-images/docs/Dockerfile
- ci-images/docs/cmake.list
- ci-images/lint/Dockerfile
- refresh-ci-images.sh
Update CMake version in docs image and clean up Dockerfiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/389)
> Updated circleci images

- .github/workflows/CI.yml
- README.md
- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/385)
> Create GitHub Actions

- src/C-interface/csr/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/393)
> Cmake: fix super-build

- src/C-interface/bml_copy.c
- src/C-interface/csr/bml_threshold_csr_typed.c
- src/C-interface/csr/bml_utilities_csr_typed.c
This PR includes a minor change to fix issues observed in testing with the SP2 algorithm. It also contains some minor edits to cleanup some benign warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/394)
> CSR bugfix

- CMakeLists.txt
- build.sh
- src/C-interface/dense/bml_diagonalize_dense.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/395)
> Add option to use cuSOLVER for dense diagonalization

- src/C-interface/ellblock/bml_setters_ellblock_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/396)
> Commented print

- src/C-interface/ellblock/bml_threshold_ellblock_typed.c
- tests/C-tests/threshold_matrix_typed.c
* this complement test on bml_threshold_new()
* fix bug in this function for ellblock format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/399)
> Add test for function bml_threshold()

- src/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/400)
> cmake: always link libm

- CMakeLists.txt
- build.sh
- src/C-interface/bml_allocate.c
- src/C-interface/ellblock/bml_add_ellblock_typed.c
- src/C-interface/ellblock/bml_allocate_ellblock.c
- src/C-interface/ellblock/bml_allocate_ellblock.h
- src/C-interface/ellblock/bml_allocate_ellblock_typed.c
- src/C-interface/ellblock/bml_convert_ellblock_typed.c
- src/C-interface/ellblock/bml_copy_ellblock_typed.c
- src/C-interface/ellblock/bml_import_ellblock_typed.c
- src/C-interface/ellblock/bml_multiply_ellblock_typed.c
- src/C-interface/ellblock/bml_setters_ellblock_typed.c
- src/C-interface/ellblock/bml_threshold_ellblock_typed.c
- src/C-interface/ellblock/bml_transpose_ellblock_typed.c
- src/C-interface/ellblock/bml_types_ellblock.h
- src/C-interface/ellblock/bml_utilities_ellblock_typed.c
- src/Fortran-interface/bml_allocate_m.F90
- src/Fortran-interface/bml_c_interface_m.F90
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/398)
> Add memory pool for ellblock

- CMakeLists.txt
- src/C-interface/bml_init.c
- src/C-interface/bml_shutdown.c
* call libxsmm_init() and libxsmm_finalize()
* add link to blas after libxsmm in cmake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/402)
> Fix a couple of minor issues with libxsmm

- src/C-interface/ellblock/bml_multiply_ellblock_typed.c
- tests/C-tests/multiply_matrix_typed.c
- tests/C-tests/multiply_matrix_x2_typed.c
Optimize small matrix multiplications when libxsmm is not available
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/401)
> Ellblock optimization

- src/C-interface/ellblock/bml_allocate_ellblock.c
- src/C-interface/ellblock/bml_allocate_ellblock_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/405)
> Fix a couple of bugs in ellblock

- docs/index.md
Added contributors in the webpage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/407)
> Added contributors to webpage

- src/C-interface/csr/bml_add_csr_typed.c
- src/C-interface/csr/bml_allocate_csr.c
- src/C-interface/csr/bml_allocate_csr.h
- src/C-interface/csr/bml_introspection_csr.c
- src/C-interface/ellblock/bml_add_ellblock_typed.c
- src/C-interface/ellpack/bml_add_ellpack_typed.c
- src/C-interface/ellsort/bml_add_ellsort_typed.c
- tests/C-tests/inverse_matrix_typed.c
This PR applies updates to optimize the bml-add-identity function for the sparse different formats. It also enables the use of openMP for the bml-add-csr function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/408)
> Update add identity

- CMakeLists.txt
- src/C-interface/bml_init.c
- src/C-interface/bml_init.h
- src/C-interface/bml_parallel.c
- src/C-interface/bml_parallel.h
- src/C-interface/bml_shutdown.c
- tests/C-tests/bml_test.c
- tests/Fortran-tests/testf.F90
Even though we are not using it now, a few things were not right with MPI calls and needed to be fixed before we can start developing a distributed BML capability
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/411)
> Cleanup MPI init/finalize

- .github/workflows/CI.yml
- Dockerfile
This will enable custom built containers for CI testing that can be
updated in the repository and then used in CI or locally for testing
and development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/417)
> Add docker build to workflows

- Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/419)
> Use newly built CI image for testing

- .github/workflows/CI.yml
This will allow the migration of our Travis-CI tests to the GitHub
Action CI framework.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/424)
> Start adding matrix tests

- .github/workflows/CI.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/425)
> Add more tests to the matrix job

- Dangerfile
It sometimes has some "strange" suggestions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/426)
> Disable prose linter

- CODEOWNERS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/427)
> Add Jamal as a CODEOWNER

- .github/workflows/CI.yml
This makes for slightly more readable code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/428)
> Compactify the matrix description

- Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/429)
> Install the `mpirun` binary for MPI tests

- src/C-interface/bml_norm.c
- src/C-interface/bml_norm.h
- src/C-interface/csr/bml_norm_csr.c
- src/C-interface/csr/bml_norm_csr.h
- src/C-interface/csr/bml_norm_csr_typed.c
- src/C-interface/dense/bml_norm_dense.c
- src/C-interface/dense/bml_norm_dense.h
- src/C-interface/dense/bml_norm_dense_typed.c
- src/C-interface/ellblock/bml_norm_ellblock.c
- src/C-interface/ellblock/bml_norm_ellblock.h
- src/C-interface/ellblock/bml_norm_ellblock_typed.c
- src/C-interface/ellblock/bml_utilities_ellblock.h
- src/C-interface/ellblock/bml_utilities_ellblock_typed.c
- src/C-interface/ellpack/bml_norm_ellpack.c
- src/C-interface/ellpack/bml_norm_ellpack.h
- src/C-interface/ellpack/bml_norm_ellpack_typed.c
- src/C-interface/ellsort/bml_norm_ellsort.c
- src/C-interface/ellsort/bml_norm_ellsort.h
- src/C-interface/ellsort/bml_norm_ellsort_typed.c
- src/Fortran-interface/bml_c_interface_m.F90
- src/Fortran-interface/bml_norm_m.F90
- tests/C-tests/norm_matrix_typed.c
add the product of two matrices, i.e., sum_{ij}A_{ij}B_{ij}.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/412)
> Product of two matrices

- .github/workflows/CI.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/430)
> Fix spelling of Fortran tests for CI

- build.sh
> Fix parsing syntax issue

- src/C-interface/dense/bml_introspection_dense_typed.c
- src/C-interface/dense/bml_threshold_dense_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/436)
> Fix a few functions for GPU/dense format

- scripts/build_olcf_summit_gnu_mgma_openblas.sh
We can save some time to users and developers by adding working build
scripts for a few platforms
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/439)
> Add build script for Summit (OLCF)

- src/C-interface/bml_add.c
- src/C-interface/bml_copy.c
- src/C-interface/bml_introspection.c
- src/C-interface/bml_scale.c
- src/C-interface/distributed2d/CMakeLists.txt
- src/C-interface/distributed2d/bml_add_distributed2d.c
- src/C-interface/distributed2d/bml_add_distributed2d.h
- src/C-interface/distributed2d/bml_allocate_distributed2d.c
- src/C-interface/distributed2d/bml_copy_distributed2d.c
- src/C-interface/distributed2d/bml_copy_distributed2d.h
- src/C-interface/distributed2d/bml_export_distributed2d.c
- src/C-interface/distributed2d/bml_import_distributed2d_typed.c
- src/C-interface/distributed2d/bml_introspection_distributed2d.c
- src/C-interface/distributed2d/bml_introspection_distributed2d.h
- src/C-interface/distributed2d/bml_scale_distributed2d.c
- src/C-interface/distributed2d/bml_scale_distributed2d.h
- src/C-interface/distributed2d/bml_types_distributed2d.h
- tests/C-tests/CMakeLists.txt
- tests/C-tests/add_matrix_typed.c
- tests/C-tests/copy_matrix_typed.c
- tests/C-tests/scale_matrix_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/446)
> Copy, add, and scale functionalities for distributed2d

- build.sh
- src/C-interface/bml_multiply.c
- src/C-interface/bml_parallel.c
- src/C-interface/bml_utilities.c
- src/C-interface/bml_utilities.h
- src/C-interface/distributed2d/CMakeLists.txt
- src/C-interface/distributed2d/bml_allocate_distributed2d.c
- src/C-interface/distributed2d/bml_multiply_distributed2d.c
- src/C-interface/distributed2d/bml_multiply_distributed2d.h
- src/C-interface/distributed2d/bml_multiply_distributed2d_typed.c
- src/C-interface/distributed2d/bml_types_distributed2d.h
- src/CMakeLists.txt
- tests/C-tests/CMakeLists.txt
- tests/C-tests/multiply_matrix_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/444)
> Cannon algorithm for distributed2d

- README.md
- docs/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/448)
> Remove CircleCI badge from docs

- tests/C-tests/convert_matrix_typed.c
- tests/C-tests/import_export_matrix_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/449)
> Swap inconsistent names in test functions

- scripts/build_tulip_magma_cce.sh
- scripts/setenv_tulip.sh
- src/C-interface/dense/bml_diagonalize_dense.c
- src/C-interface/ellpack/bml_multiply_ellpack_typed.c
- tests/Fortran-tests/io_matrix_typed.F90
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/447)
> Modifications and scripts to build on tulip

- src/C-interface/bml_convert.c
- src/C-interface/bml_introspection.c
- src/C-interface/bml_introspection.h
- src/C-interface/distributed2d/CMakeLists.txt
- src/C-interface/distributed2d/bml_allocate_distributed2d.c
- src/C-interface/distributed2d/bml_convert_distributed2d.c
- src/C-interface/distributed2d/bml_convert_distributed2d.h
- src/C-interface/distributed2d/bml_import_distributed2d_typed.c
- src/C-interface/distributed2d/bml_introspection_distributed2d.c
- src/C-interface/distributed2d/bml_introspection_distributed2d.h
- src/C-interface/ellpack/bml_allocate_ellpack_typed.c
- tests/C-tests/CMakeLists.txt
- tests/C-tests/convert_matrix_typed.c
- tests/C-tests/import_export_matrix_typed.c
Bug fix
Memory leak fix
Turn on some extra testing
Implement convert function for distributed2d format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/450)
> Fixes for distributed2d format

- .github/workflows/CI.yml
In case the job does not set a particular environment variable fall
back to the default environment variable value.
> Use default environment variables

- prepare-container.sh
> Retry repository update in case of network issues

- .github/workflows/CI.yml
> Add periodic CI job

- CMakeLists.txt
> Remove `BML_COVERAGE` flag

- .github/workflows/CI.yml
- prepare-container.sh
> Start testing with gcc-11

- .github/workflows/container.yaml
> Upgrade to most recent version of docker action

- scripts/build_iris_offload_oneapi.sh
- scripts/setenv_iris.sh
- src/C-interface/csr/bml_multiply_csr_typed.c
- src/C-interface/ellpack/bml_add_ellpack_typed.c
- src/C-interface/ellpack/bml_multiply_ellpack_typed.c
- src/macros.h
- tests/C-tests/multiply_matrix_typed.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/457)
> Support OpenMP GPU offload on iris nodes at ANL

- .github/workflows/container.yaml
> Periodically build the container image

- Dockerfile
> Add maintainer to Dockerfile

- scripts/indent.sh
- src/Fortran-interface/bml_setters_m.F90
- tests/Fortran-tests/convert_matrix_typed.F90
- tests/Fortran-tests/prec.F90
- tests/Fortran-tests/precision.F90
- tests/Fortran-tests/testf.F90
> Add `whitespace-cleanup` to indent check

- .github/workflows/CI.yaml
- CMakeLists.txt
- build.sh
> CI test `Debug` build type

- Dockerfile-focal
- Dockerfile-hirsute
- Dockerfile-impish
- scripts/prepare-container-focal.sh
- scripts/prepare-container-hirsute.sh
- scripts/prepare-container-impish.sh
This is a 'preview' of using more recent Ubuntu series as base for the
CI containers.
> Add Focal, Impish, and Hirsute as potential CI base

- .github/workflows/container.yaml
> Check out project before running Docker

- CMakeLists.txt
> Update project version in `CMakeLists.txt`

- CMakeLists.txt
> Version bump to v2.0.1

- .github/workflows/CI.yaml
- scripts/ci-clang-11-gfortran-11-C-double-complex.sh
- scripts/ci-clang-11-gfortran-11-C-double-real.sh
- scripts/ci-clang-11-gfortran-11-C-single-complex.sh
- scripts/ci-clang-11-gfortran-11-C-single-real.sh
- scripts/prepare-container.sh
> Add mixed clang/gcc tests

- CMakeLists.txt
> Version bump to v2.1.0

- .dir-locals.el
- scripts/indent.sh
> Fix dir local variables

- examples/sparse-matrix/gen-sparse.c
Added a .c file to /bml/examples/sparse-matrix/ that generates a sparse Hamiltonian matrix using the example Hamiltonian shown in https://doi.org/10.1021/acs.jctc.1c00057
> added sparse matrix example

- src/C-interface/distributed2d/bml_transpose_distributed2d.c
Previous version passed the tests, but maybe only because
matrices in test suite are really small. For larger matrices,
blocking MPI calls hang
> Bug fix in transpose for distributed2d

- src/C-interface/distributed2d/bml_transpose_distributed2d.c
This fixes a deadlock seen for matrices larger than those
in test suite
> Use irecv in distributed transpose

- src/Fortran-interface/bml_c_interface_m.F90
- src/Fortran-interface/bml_export_m.F90
- src/Fortran-interface/bml_import_m.F90
- src/Fortran-interface/bml_parallel_m.F90
- tests/CMakeLists.txt
- tests/Fortran-tests/CMakeLists.txt
- tests/Fortran-tests/copy_matrix_typed.F90
Implement functionalities to do that, and setup one
complete test.
> Enable testing Fortran interface with MPI

- .github/workflows/stale.yaml
> Add workflow to check for stale issues and PRs

- .gitignore
> Ignore local worktrees

- README.rst
- docs/Makefile
> Fixup the style of the rst documentation

- README.rst
> Make list style consistent

- docs/source/requirements.txt
> Upgrade pinned package versions

- CMakeLists.txt
- build.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lanl/bml/370)
> Shorten paths in `__FILE__` expansion

- .github/workflows/CI.yaml
- build.sh
- scripts/prepare-container-focal.sh
- scripts/prepare-container-hirsute.sh
- scripts/prepare-container-impish.sh
- scripts/prepare-container.sh
> Also lint the shell scripts

- README.rst
Add some instructions on how to generate assembly from C in order to understand
better whether the compiler optimizes the code.
> Add example for assembly generation

- README.rst
> Fix which line is highlighted

- scripts/build_olcf_summit_gnu_mpi_esslsmp.sh
Uses gcc, esslsmp, MPI, and scalapack
> Add build script for summit at OLCF

- .github/workflows/CI.yaml
- scripts/ci-clang-12-gfortran-11-C-double-complex.sh
- scripts/ci-clang-12-gfortran-11-C-double-real.sh
- scripts/ci-clang-12-gfortran-11-C-single-complex.sh
- scripts/ci-clang-12-gfortran-11-C-single-real.sh
- scripts/prepare-container.sh
> Upgrade CI to llvm-12

- .github/workflows/stale.yaml
> Upgrade `stale` action to latest release

- .github/workflows/CI.yaml
- .gitignore
- CMakeLists.txt
- src/C-interface/bml_logger.c
- src/C-interface/bml_logger.c.indented
- src/C-interface/bml_logger.h
- src/C-interface/bml_logger.h.indented
- src/CMakeLists.txt
- src/bml_version.c
This change adds a C function that returns the library version string. This
string will include a git commit hash if the library was built from git source.
Closes: lanl/bml#621
> Add `BML_VERSION`

- .gitignore
- CMakeLists.txt
> Add `indented` files to `gitignore`

- scripts/build_olcf_summit_gnu_offload_openblas.sh
> Add build script for GPU offload on Summit

- scripts/prepare-container-focal.sh
- scripts/prepare-container.sh
> Add `less` to CI container

- Dockerfile
- Dockerfile-focal
> Updated deprecated Dockerfile commands

- .github/workflows/CI.yaml
- scripts/prepare-container.sh
> Test with OpenBLAS as an alternative

- src/C-interface/dense/bml_getters_dense_typed.c
Use bml allocation functions instead of calloc
> Fix some compiler warnings related to calloc

- CMakeLists.txt
We are not using OpenCL at all
> Remove OpenCL from CMakeLists.txt

- src/C-interface/ellpack/bml_transpose_ellpack.h
- src/C-interface/ellpack/bml_transpose_ellpack_typed.c
This PR Adds new functionality for ellpack's transpose using openMP OFFLOAD + cusparse
> Added cusparse capability for bml_transpose_ellpack.

- tests/C-tests/norm_matrix_typed.c
Scale tolerance with number of non-zero.
Now required for distribuide case which uses bigger matrices.
> Fix tolerance in matrix norm test

- CMakeLists.txt
> Fix link line in bml.pc

- README.rst
> Add Docker Hub badge

- src/C-interface/bml_logger.c
- src/C-interface/bml_logger.h
- src/Fortran-interface/CMakeLists.txt
- src/Fortran-interface/bml.F90
- src/Fortran-interface/bml_c_interface_m.F90
- src/Fortran-interface/bml_logger_m.F90
- tests/C-tests/bml_test.c
- tests/Fortran-tests/testf.F90
Closes: https://github.com/lanl/bml/issues/692
> Expose `bml_print_version` to Fortran

- scripts/indent.sh
> Print diff if linter failure

- scripts/build_crusher_rocsparse_cce.sh
- scripts/setenv_crusher_offload_rocm_5.3.sh
- src/C-interface/ellpack/bml_add_ellpack_typed.c
o Add build script for CCE 15 and rocm 5.3
o Add -hsystem_alloc to Fortran flags
o Fix OMP offload macro test in bml_add_ellpack
> Debug bml_add_ellpack and Fortran build on crusher

- scripts/build_mkl_gpu.sh
- src/C-interface/dense/bml_allocate_dense.c
- src/C-interface/dense/bml_allocate_dense.h
- src/C-interface/dense/bml_allocate_dense_typed.c
- src/C-interface/dense/bml_copy_dense_typed.c
Fixing issues with dense offload on Intel
> Dense offload

- CMakeLists.txt
- build.sh
- src/C-interface/dense/bml_diagonalize_dense.c
- src/C-interface/lapack.h
Make it default option for dense diagonalization
> Add build time option of using syevd

- Dockerfile-focal
> Set bash shell for devcontainer user

- .devcontainer/devcontainer.json
> Add some default extensions to devcontainer

- scripts/prepare-container-focal.sh
> Add doxygen package for API builds

- src/C-interface/dense/bml_diagonalize_dense.c
> Separate real offload diagonalize routines.

- src/C-interface/ellpack/bml_multiply_ellpack_typed.c
New check is after thresholding product, not before
> Change check for excess column in ellpack x2

- scripts/build_crusher_cce.sh
- scripts/setenv_crusher_cce.sh
This one enables both OpenMP offload and MAGMA together
> Add scripts for cray compiler on AMD

- .readthedocs.yaml
- docs/source/requirements.txt
> Update readthedocs build configuration

- .github/workflows/CI.yaml
> Fix syntax error in workflow

- .github/workflows/CI.yaml
- .github/workflows/container.yaml
> Update GitHub checkout action

- .devcontainer/devcontainer.json
Helpful when editing workflow files.
> Add yaml extension to dev container

- .devcontainer/devcontainer.json
> Add another VSCode extension to container

- .github/workflows/CI.yaml
> Update version of artifact action

- .github/workflows/CI.yaml
- scripts/ci-gcc-14-C-double-complex.sh
- scripts/ci-gcc-14-C-double-real.sh
- scripts/ci-gcc-14-C-single-complex.sh
- scripts/ci-gcc-14-C-single-real.sh
- scripts/ci-gcc-14-Fortran-double-complex.sh
- scripts/ci-gcc-14-Fortran-double-real.sh
- scripts/ci-gcc-14-Fortran-single-complex.sh
- scripts/ci-gcc-14-Fortran-single-real.sh
> Update compiler for OS X runner

- .github/workflows/CI.yaml
- CMakeLists.txt
> Update CI to use Jammy image

- .github/workflows/CI.yaml
> Add merge group trigger
